services:
  chat_analyzer_api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ConnectionStrings__DefaultConnection=Host=chat_analyzer_db;Port=5432;Database=chat_analyzer_db;Username=user;Password=password
    depends_on:
      - chat_analyzer_db

  chat_analyzer_db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chat_analyzer_db
    ports:
      - "5432:5432"
    volumes:
      - chat_analyzer_db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    depends_on:
      - chat_analyzer_api

volumes:
  chat_analyzer_db_data:
    driver: local
