name: Run xUnit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        working-directory: ./backend
        run: dotnet restore ChatAnalyzer.sln

      - name: Build the project
        working-directory: ./backend
        run: dotnet build ChatAnalyzer.sln --configuration Release --no-restore

      - name: Run xUnit tests
        working-directory: ./backend
        run: dotnet test ChatAnalyzer.UnitTests --configuration Release --no-build --logger trx --results-directory TestResults
